version: "2"

run:
    timeout: 5m
    tests: true

issues:
    max-issues-per-linter: 0
    max-same-issues: 0

linters:
    default: none
    enable:
        - errcheck
        - govet
        - staticcheck
        - ineffassign
        - unused
        - revive
        - unconvert
        - misspell
        - copyloopvar
        - gocritic
    settings:
        errcheck:
            check-type-assertions: true
        govet:
            enable-all: true
            disable:
                - fieldalignment
        revive:
            rules:
                - name: blank-imports
                - name: context-as-argument
                - name: context-keys-type
                - name: dot-imports
                - name: empty-block
                - name: error-return
                - name: error-strings
                - name: if-return
                - name: increment-decrement
                - name: range
                - name: receiver-naming
                - name: redefines-builtin-id
                - name: superfluous-else
                - name: unreachable-code
                - name: unused-parameter
